
Vagrant.configure("2") do |config|
  config.vm.define "dapariciS" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "dapariciS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "dapariciS"
      vb.memory = "2048"
      vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "dapariciSW" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "dapariciSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "dapariciSW"
      vb.memory = "2048"
      vb.cpus = 2
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
