apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot-p3
servers: 1
agents: 1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
